### ISSUE TITLE
Session attributes not able to cast List of custom model objects even thought the models are serializable

### ISSUE THREAD

**Issue by vCillusion** [alexa/alexa-skills-kit-sdk-for-java#79]
Hi Team
Session Attributes are not able to retrieve any list defined in custom POJO model.
`List<Question> questions;`
```
public class Question implements Serializable{
	
	/** The question id. */
	private Long id;
	
	/** The question text. */
	private String quesText;
```

**Comment by janknobloch** [comment]
Some time ago I used the jackson objectmapper to create what you planning to achieve.
However 👍 for the idea of allowing custom pojos to be put as attributes.

**Comment by sungolivia** [comment]
You should be able to achieve this using AttributesManager to retrieve session attributes and ObjectMapper like @janknobloch mentioned. Can you show us the code where you retrieve and rest of the implementation for Question class?

**Comment by Bergmaier** [comment]
Can you add documentation to `AttributesManager` on how this could work? What do I need to annotate my POJO classes with so that they can be serialised when I put them in the session attributes?

I was trying to do something along the lines of
```java
public class Question implements Serializable {
	...
	static ObjectMapper mapper = new ObjectMapper();
	public static Question fromSession(AttributeManager m) {
		Object q = m.getSessionAttributes.get("q");
		if (q != null)
			return mapper.convertValue(q, Question.class);
		return new Question();
	}
}
```
The other way round, `sessionAttributes.put("q", question)`, works just fine and I can see the expected JSON response in the Alexa console.
