### ISSUE TITLE
SDK 2.0: Missing Jackson-databind import

### ISSUE THREAD

**Issue by janknobloch** [alexa/alexa-skills-kit-sdk-for-java#90]
When using framework 2.2 with the following dependencies:

```

<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk-core</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk-lambda-support</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk-dynamodb-persistence-adapter</artifactId>
			<version>2.0.2</version>
		</dependency>
```

The following dependency is missing:
```
	<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
		</dependency>
```

## Expected Behavior

The framework should run without issues only using the stated dependencies in your MD files.

Add a Jackson sub-dependency to your dependency list :

```
<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
		</dependency>

```

## Current Behavior
The skills fails due to missing packages of jackson databind when deploying with AWS lambda as its needed inside of: class RequestEnvelope amongst others.

**Comment by janknobloch** [comment]
sorry for the late reply:
hereby id like to share my full pom as the error seems to persist after removing my manual databind import.

`<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>MyTestSkill</groupId>
	<artifactId>MyTestSkill</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<properties>
		<jackson.version>2.9.0</jackson.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk-core</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk-lambda-support</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk-dynamodb-persistence-adapter</artifactId>
			<version>2.0.2</version>
		</dependency>

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-core</artifactId>
			<version>1.2.0</version>
		</dependency>
	</dependencies>

</project>`

It looks like this issure occurs due to: 
ask-sdk-dynamodb-persistence-adapter:2.0.2 uses jackson-databind 2.6.7.1
and ask-sdk-core:2.0.2 -> ask-sdk-model:1.0.0 uses jackson-databind 2.9.4

which leads to some conflicts and therefore ommited dependencies.

Best
Jan

**Comment by sungolivia** [comment]
Hey there, apologies on late reply.
This is what my mvn dependency:tree spits out when I run the command on ask-sdk-dynamodb-persistence-adapter package.

[INFO] ------------------------------------------------------------------------
[INFO] Building ASK SDK for Java DynamoDB Persistence Adapter 2.0.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ask-sdk-dynamodb-persistence-adapter ---
[INFO] com.amazon.alexa:ask-sdk-dynamodb-persistence-adapter:jar:2.0.2
[INFO] +- com.amazon.alexa:ask-sdk-core:jar:2.0.2:compile
[INFO] |  +- com.amazon.alexa:ask-sdk-model:jar:1.0.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.4:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.4:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.4:compile
...

So I see that it's 2.9.4 since it's pulling from core pacakge, do you mind showing me how you got 2.6.7.1? Thanks!
